### ISSUE TITLE
Enhancement on displaying events list  

### ISSUE THREAD

**Issue by yuri01** [InternetProject/Thing1#21]
Event plugin - split upcoming events and past events

**Comment by panezg** [comment]
I on purpose pulled all events because there was so little data in the db. I can fix it quickly.

**Comment by yuri01** [comment]
Thanks!!!

Sent from my iPhone

On Feb 8, 2017, at 1:47 PM, panezg <notifications@github.com<mailto:notifications@github.com>> wrote:


I on purpose pulled all events because there was so little data in the db. I can fix it quickly.

**Comment by panezg** [comment]
Fixed.
