### ISSUE TITLE
Membership options: Defined end date or 365 days from purchase?

### ISSUE THREAD

**Issue by RobMGibson** [InternetProject/Thing1#26]

**Comment by panezg** [comment]
Membership options have a Expiration Date defined at creation time. This is the date used in the SelectMembershipOption page. Waiting for confirmation.

**Comment by tladle** [comment]
I believe it was decided that we should let the club officer "hard code" in the exact date a membership was set to expire. This was to give them more flexibility in membership option creation.

**Comment by panezg** [comment]
Ok, then I guess there is nothing to fix here?
