### ISSUE TITLE
Payment Confirmation page - Display user first and last name 

### ISSUE THREAD

**Issue by RobMGibson** [InternetProject/Thing1#29]
Current payment confirmation page shows username (email). Should have user's first and last name

**Comment by panezg** [comment]
Is this even required? There is already a salutation in the header of all pages
![image](https://cloud.githubusercontent.com/assets/22795659/22908035/289a95b0-f244-11e6-9bf4-e9f303498b14.png)

**Comment by RobMGibson** [comment]
ideally, the header would use the user's first name rather than username anyway. 

But for payment confirmation, I think using the name is important:

![image](https://cloud.githubusercontent.com/assets/22670712/22908926/f5396018-f205-11e6-9a49-ccf0be7166f6.png)

**Comment by RobMGibson** [comment]
Especially since it just has the name with an exclamation point

**Comment by panezg** [comment]
Fixed.
I changed the salutation in the header of the site and in the confirmation page of paypal payment
We may need to make another change to have that piece of code in a single place

**Comment by panezg** [comment]
If the user has a name in the DB the app will use this info instead of the username. If the user has a name and a last name the app will use both.
We may need more code to update that information on memory when users change their profile information
