### ISSUE TITLE
Event - RSVPs

### ISSUE THREAD

**Issue by jamierowles86** [InternetProject/Thing1#36]
Solving for use case: As a club officer, I want to see how many students have RSVP'd to an event so that I can order food.

 - Right now there is a page “.../events/rsvps” that shows all RSVPs for all events
 - There should be a page for all rsvps for a specific event

**Comment by siddharthshah1** [comment]
Seems like an issue that Calendar team would be better suited to taking point on.

**Comment by shawnstolsig** [comment]
This is the same as issue #34, which I am working on. So closing this one.
