### ISSUE TITLE
Remove/Hide columns on ".../ClubMembersList/Index/[clubID]" page

### ISSUE THREAD

**Issue by RobMGibson** [InternetProject/Thing1#37]
On the page to view club members we should remove/hide the following:

- Name (the club name, on the right).

- Description (on the right, which shows the type of membership)

- Description (on the right, which is determined by RoleID)

- Violation

**Comment by warrenshhsiao** [comment]
Agree that club name, types of membership and RoleID should be removed. Why remove Violation?

**Comment by RobMGibson** [comment]
For the purposes of presenting to Gary, Violation is a feature that doesn't work right now, so we thought hiding it temporarily was a good idea. If not, then we should at least change the appearance

**Comment by warrenshhsiao** [comment]
Will do.
