### ISSUE TITLE
membership option

### ISSUE THREAD

**Issue by iriscyt** [InternetProject/Thing1#47]
adding alumni/ others to the drop down menu _**for membership type._**

**Comment by dakinfenwa** [comment]
@iriscyt just to be clear, this is referring to membership TYPE, correct? In addition to student and sig-o membership type? cc @tladle @anini311  @JustinGYee

**Comment by iriscyt** [comment]
correct. this is what liz was asking. @dakinfenwa @tladle @anini311 @JustinGYee

**Comment by tladle** [comment]
Added the alumni type in the database
