### ISSUE TITLE
MBA Class should be a required field when signing up

### ISSUE THREAD

**Issue by tladle** [InternetProject/Thing1#53]
Currently it is not required and this needs to be changed

**Comment by dakinfenwa** [comment]
@tladle what page is this referring to? Is it the /Account/Register page? B/c this page doesn't currently ask for the MBA class

**Comment by tladle** [comment]
Yes that is what this is referring to, sorry my wording was off but the idea was that there should be a field for someone to enter in their class type and graduation date (e.g. FT MBA 2017) and that it should be required. This will help with future searching across club alumni

**Comment by tladle** [comment]
Fixed it is now part of the register page
