### ISSUE TITLE
"back to list" from Join Club page

### ISSUE THREAD

**Issue by shawnstolsig** [InternetProject/Thing1#9]
when you click "back to list" when you are Join Club page, it sends you to a list of membership options instead of the list of clubs

**Comment by dakinfenwa** [comment]
I believe this was fixed in https://github.com/InternetProject/Thing1/commit/b0742aad191f744ee620be892dc733fa031bfdd4

Can you pull code and confirm? If so, please close ticket. Thanks. @shawnstolsig
